/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvoiceDataRowModel from './InvoiceDataRowModel';
import PaymentDataRowModel from './PaymentDataRowModel';
import PurchaseDataRowModel from './PurchaseDataRowModel';

/**
 * The FinancialDataModel model module.
 * @module model/FinancialDataModel
 * @version 1.0
 */
class FinancialDataModel {
    /**
     * Constructs a new <code>FinancialDataModel</code>.
     * @alias module:model/FinancialDataModel
     */
    constructor() { 
        
        FinancialDataModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FinancialDataModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FinancialDataModel} obj Optional instance to populate.
     * @return {module:model/FinancialDataModel} The populated <code>FinancialDataModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FinancialDataModel();

            if (data.hasOwnProperty('monthlyCardRevenue')) {
                obj['monthlyCardRevenue'] = ApiClient.convertToType(data['monthlyCardRevenue'], 'Number');
            }
            if (data.hasOwnProperty('paymentData')) {
                obj['paymentData'] = ApiClient.convertToType(data['paymentData'], [PaymentDataRowModel]);
            }
            if (data.hasOwnProperty('monthlyValueOfPurchaseTransactions')) {
                obj['monthlyValueOfPurchaseTransactions'] = ApiClient.convertToType(data['monthlyValueOfPurchaseTransactions'], 'Number');
            }
            if (data.hasOwnProperty('purchaseData')) {
                obj['purchaseData'] = ApiClient.convertToType(data['purchaseData'], [PurchaseDataRowModel]);
            }
            if (data.hasOwnProperty('monthlyRevenueFromInvoices')) {
                obj['monthlyRevenueFromInvoices'] = ApiClient.convertToType(data['monthlyRevenueFromInvoices'], 'Number');
            }
            if (data.hasOwnProperty('invoiceData')) {
                obj['invoiceData'] = ApiClient.convertToType(data['invoiceData'], [InvoiceDataRowModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} monthlyCardRevenue
 */
FinancialDataModel.prototype['monthlyCardRevenue'] = undefined;

/**
 * @member {Array.<module:model/PaymentDataRowModel>} paymentData
 */
FinancialDataModel.prototype['paymentData'] = undefined;

/**
 * @member {Number} monthlyValueOfPurchaseTransactions
 */
FinancialDataModel.prototype['monthlyValueOfPurchaseTransactions'] = undefined;

/**
 * @member {Array.<module:model/PurchaseDataRowModel>} purchaseData
 */
FinancialDataModel.prototype['purchaseData'] = undefined;

/**
 * @member {Number} monthlyRevenueFromInvoices
 */
FinancialDataModel.prototype['monthlyRevenueFromInvoices'] = undefined;

/**
 * @member {Array.<module:model/InvoiceDataRowModel>} invoiceData
 */
FinancialDataModel.prototype['invoiceData'] = undefined;






export default FinancialDataModel;

