/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvoiceDataRowModel model module.
 * @module model/InvoiceDataRowModel
 * @version 1.0
 */
class InvoiceDataRowModel {
    /**
     * Constructs a new <code>InvoiceDataRowModel</code>.
     * @alias module:model/InvoiceDataRowModel
     * @param invoiceDate {Date} 
     * @param amount {Number} 
     * @param currencyISOCode {String} 
     * @param daysDurationOfInvoice {Number} 
     */
    constructor(invoiceDate, amount, currencyISOCode, daysDurationOfInvoice) { 
        
        InvoiceDataRowModel.initialize(this, invoiceDate, amount, currencyISOCode, daysDurationOfInvoice);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, invoiceDate, amount, currencyISOCode, daysDurationOfInvoice) { 
        obj['invoiceDate'] = invoiceDate;
        obj['amount'] = amount;
        obj['currencyISOCode'] = currencyISOCode;
        obj['daysDurationOfInvoice'] = daysDurationOfInvoice;
    }

    /**
     * Constructs a <code>InvoiceDataRowModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvoiceDataRowModel} obj Optional instance to populate.
     * @return {module:model/InvoiceDataRowModel} The populated <code>InvoiceDataRowModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvoiceDataRowModel();

            if (data.hasOwnProperty('invoiceDate')) {
                obj['invoiceDate'] = ApiClient.convertToType(data['invoiceDate'], 'Date');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currencyISOCode')) {
                obj['currencyISOCode'] = ApiClient.convertToType(data['currencyISOCode'], 'String');
            }
            if (data.hasOwnProperty('daysDurationOfInvoice')) {
                obj['daysDurationOfInvoice'] = ApiClient.convertToType(data['daysDurationOfInvoice'], 'Number');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} invoiceDate
 */
InvoiceDataRowModel.prototype['invoiceDate'] = undefined;

/**
 * @member {Number} amount
 */
InvoiceDataRowModel.prototype['amount'] = undefined;

/**
 * @member {String} currencyISOCode
 */
InvoiceDataRowModel.prototype['currencyISOCode'] = undefined;

/**
 * @member {Number} daysDurationOfInvoice
 */
InvoiceDataRowModel.prototype['daysDurationOfInvoice'] = undefined;

/**
 * @member {String} category
 */
InvoiceDataRowModel.prototype['category'] = undefined;






export default InvoiceDataRowModel;

