/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoanOptionDocument model module.
 * @module model/LoanOptionDocument
 * @version 1.0
 */
class LoanOptionDocument {
    /**
     * Constructs a new <code>LoanOptionDocument</code>.
     * @alias module:model/LoanOptionDocument
     */
    constructor() { 
        
        LoanOptionDocument.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoanOptionDocument</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoanOptionDocument} obj Optional instance to populate.
     * @return {module:model/LoanOptionDocument} The populated <code>LoanOptionDocument</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoanOptionDocument();

            if (data.hasOwnProperty('fundedAmount')) {
                obj['fundedAmount'] = ApiClient.convertToType(data['fundedAmount'], 'Number');
            }
            if (data.hasOwnProperty('fee')) {
                obj['fee'] = ApiClient.convertToType(data['fee'], 'Number');
            }
            if (data.hasOwnProperty('loanAmount')) {
                obj['loanAmount'] = ApiClient.convertToType(data['loanAmount'], 'Number');
            }
            if (data.hasOwnProperty('sweep')) {
                obj['sweep'] = ApiClient.convertToType(data['sweep'], 'Number');
            }
            if (data.hasOwnProperty('currencyISOCode')) {
                obj['currencyISOCode'] = ApiClient.convertToType(data['currencyISOCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} fundedAmount
 */
LoanOptionDocument.prototype['fundedAmount'] = undefined;

/**
 * @member {Number} fee
 */
LoanOptionDocument.prototype['fee'] = undefined;

/**
 * @member {Number} loanAmount
 */
LoanOptionDocument.prototype['loanAmount'] = undefined;

/**
 * @member {Number} sweep
 */
LoanOptionDocument.prototype['sweep'] = undefined;

/**
 * @member {String} currencyISOCode
 */
LoanOptionDocument.prototype['currencyISOCode'] = undefined;






export default LoanOptionDocument;

