/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentDataRowModel model module.
 * @module model/PaymentDataRowModel
 * @version 1.0
 */
class PaymentDataRowModel {
    /**
     * Constructs a new <code>PaymentDataRowModel</code>.
     * @alias module:model/PaymentDataRowModel
     * @param paymentDate {Date} 
     * @param amount {Number} 
     * @param currencyISOCode {String} 
     */
    constructor(paymentDate, amount, currencyISOCode) { 
        
        PaymentDataRowModel.initialize(this, paymentDate, amount, currencyISOCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paymentDate, amount, currencyISOCode) { 
        obj['paymentDate'] = paymentDate;
        obj['amount'] = amount;
        obj['currencyISOCode'] = currencyISOCode;
    }

    /**
     * Constructs a <code>PaymentDataRowModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentDataRowModel} obj Optional instance to populate.
     * @return {module:model/PaymentDataRowModel} The populated <code>PaymentDataRowModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentDataRowModel();

            if (data.hasOwnProperty('paymentDate')) {
                obj['paymentDate'] = ApiClient.convertToType(data['paymentDate'], 'Date');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currencyISOCode')) {
                obj['currencyISOCode'] = ApiClient.convertToType(data['currencyISOCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} paymentDate
 */
PaymentDataRowModel.prototype['paymentDate'] = undefined;

/**
 * @member {Number} amount
 */
PaymentDataRowModel.prototype['amount'] = undefined;

/**
 * @member {String} currencyISOCode
 */
PaymentDataRowModel.prototype['currencyISOCode'] = undefined;






export default PaymentDataRowModel;

