/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FinancialDataModel from './FinancialDataModel';
import SignificantPersonModel from './SignificantPersonModel';

/**
 * The PreQualificationModel model module.
 * @module model/PreQualificationModel
 * @version 1.0
 */
class PreQualificationModel {
    /**
     * Constructs a new <code>PreQualificationModel</code>.
     * @alias module:model/PreQualificationModel
     * @param thirdPartyMerchantId {String} 
     * @param companyName {String} 
     * @param companyNumber {String} 
     * @param companyType {String} 
     * @param countryISOCode {String} 
     * @param financialData {module:model/FinancialDataModel} 
     */
    constructor(thirdPartyMerchantId, companyName, companyNumber, companyType, countryISOCode, financialData) { 
        
        PreQualificationModel.initialize(this, thirdPartyMerchantId, companyName, companyNumber, companyType, countryISOCode, financialData);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, thirdPartyMerchantId, companyName, companyNumber, companyType, countryISOCode, financialData) { 
        obj['thirdPartyMerchantId'] = thirdPartyMerchantId;
        obj['companyName'] = companyName;
        obj['companyNumber'] = companyNumber;
        obj['companyType'] = companyType;
        obj['countryISOCode'] = countryISOCode;
        obj['financialData'] = financialData;
    }

    /**
     * Constructs a <code>PreQualificationModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PreQualificationModel} obj Optional instance to populate.
     * @return {module:model/PreQualificationModel} The populated <code>PreQualificationModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PreQualificationModel();

            if (data.hasOwnProperty('thirdPartyMerchantId')) {
                obj['thirdPartyMerchantId'] = ApiClient.convertToType(data['thirdPartyMerchantId'], 'String');
            }
            if (data.hasOwnProperty('mid')) {
                obj['mid'] = ApiClient.convertToType(data['mid'], 'String');
            }
            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('companyNumber')) {
                obj['companyNumber'] = ApiClient.convertToType(data['companyNumber'], 'String');
            }
            if (data.hasOwnProperty('companyType')) {
                obj['companyType'] = ApiClient.convertToType(data['companyType'], 'String');
            }
            if (data.hasOwnProperty('companyWebsite')) {
                obj['companyWebsite'] = ApiClient.convertToType(data['companyWebsite'], 'String');
            }
            if (data.hasOwnProperty('contactEmailAddress')) {
                obj['contactEmailAddress'] = ApiClient.convertToType(data['contactEmailAddress'], 'String');
            }
            if (data.hasOwnProperty('countryISOCode')) {
                obj['countryISOCode'] = ApiClient.convertToType(data['countryISOCode'], 'String');
            }
            if (data.hasOwnProperty('loanCurrencyISOCode')) {
                obj['loanCurrencyISOCode'] = ApiClient.convertToType(data['loanCurrencyISOCode'], 'String');
            }
            if (data.hasOwnProperty('sicCode')) {
                obj['sicCode'] = ApiClient.convertToType(data['sicCode'], 'String');
            }
            if (data.hasOwnProperty('mccCode')) {
                obj['mccCode'] = ApiClient.convertToType(data['mccCode'], 'String');
            }
            if (data.hasOwnProperty('monthsTrading')) {
                obj['monthsTrading'] = ApiClient.convertToType(data['monthsTrading'], 'Number');
            }
            if (data.hasOwnProperty('financialData')) {
                obj['financialData'] = FinancialDataModel.constructFromObject(data['financialData']);
            }
            if (data.hasOwnProperty('significantPersons')) {
                obj['significantPersons'] = ApiClient.convertToType(data['significantPersons'], [SignificantPersonModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} thirdPartyMerchantId
 */
PreQualificationModel.prototype['thirdPartyMerchantId'] = undefined;

/**
 * @member {String} mid
 */
PreQualificationModel.prototype['mid'] = undefined;

/**
 * @member {String} companyName
 */
PreQualificationModel.prototype['companyName'] = undefined;

/**
 * @member {String} companyNumber
 */
PreQualificationModel.prototype['companyNumber'] = undefined;

/**
 * @member {String} companyType
 */
PreQualificationModel.prototype['companyType'] = undefined;

/**
 * @member {String} companyWebsite
 */
PreQualificationModel.prototype['companyWebsite'] = undefined;

/**
 * @member {String} contactEmailAddress
 */
PreQualificationModel.prototype['contactEmailAddress'] = undefined;

/**
 * @member {String} countryISOCode
 */
PreQualificationModel.prototype['countryISOCode'] = undefined;

/**
 * @member {String} loanCurrencyISOCode
 */
PreQualificationModel.prototype['loanCurrencyISOCode'] = undefined;

/**
 * @member {String} sicCode
 */
PreQualificationModel.prototype['sicCode'] = undefined;

/**
 * @member {String} mccCode
 */
PreQualificationModel.prototype['mccCode'] = undefined;

/**
 * @member {Number} monthsTrading
 */
PreQualificationModel.prototype['monthsTrading'] = undefined;

/**
 * @member {module:model/FinancialDataModel} financialData
 */
PreQualificationModel.prototype['financialData'] = undefined;

/**
 * @member {Array.<module:model/SignificantPersonModel>} significantPersons
 */
PreQualificationModel.prototype['significantPersons'] = undefined;






export default PreQualificationModel;

