/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoanOptionDocument from './LoanOptionDocument';

/**
 * The PreQualificationResultDocument model module.
 * @module model/PreQualificationResultDocument
 * @version 1.0
 */
class PreQualificationResultDocument {
    /**
     * Constructs a new <code>PreQualificationResultDocument</code>.
     * @alias module:model/PreQualificationResultDocument
     */
    constructor() { 
        
        PreQualificationResultDocument.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PreQualificationResultDocument</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PreQualificationResultDocument} obj Optional instance to populate.
     * @return {module:model/PreQualificationResultDocument} The populated <code>PreQualificationResultDocument</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PreQualificationResultDocument();

            if (data.hasOwnProperty('thirdPartyMerchantId')) {
                obj['thirdPartyMerchantId'] = ApiClient.convertToType(data['thirdPartyMerchantId'], 'String');
            }
            if (data.hasOwnProperty('mid')) {
                obj['mid'] = ApiClient.convertToType(data['mid'], 'String');
            }
            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('overallCreditRiskScore')) {
                obj['overallCreditRiskScore'] = ApiClient.convertToType(data['overallCreditRiskScore'], 'Number');
            }
            if (data.hasOwnProperty('overrideCreditRiskScore')) {
                obj['overrideCreditRiskScore'] = ApiClient.convertToType(data['overrideCreditRiskScore'], 'Number');
            }
            if (data.hasOwnProperty('loanOptions')) {
                obj['loanOptions'] = ApiClient.convertToType(data['loanOptions'], [LoanOptionDocument]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} thirdPartyMerchantId
 */
PreQualificationResultDocument.prototype['thirdPartyMerchantId'] = undefined;

/**
 * @member {String} mid
 */
PreQualificationResultDocument.prototype['mid'] = undefined;

/**
 * @member {String} companyName
 */
PreQualificationResultDocument.prototype['companyName'] = undefined;

/**
 * @member {Number} overallCreditRiskScore
 */
PreQualificationResultDocument.prototype['overallCreditRiskScore'] = undefined;

/**
 * @member {Number} overrideCreditRiskScore
 */
PreQualificationResultDocument.prototype['overrideCreditRiskScore'] = undefined;

/**
 * @member {Array.<module:model/LoanOptionDocument>} loanOptions
 */
PreQualificationResultDocument.prototype['loanOptions'] = undefined;






export default PreQualificationResultDocument;

