/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PurchaseDataRowModel model module.
 * @module model/PurchaseDataRowModel
 * @version 1.0
 */
class PurchaseDataRowModel {
    /**
     * Constructs a new <code>PurchaseDataRowModel</code>.
     * @alias module:model/PurchaseDataRowModel
     * @param purchaseDate {Date} 
     * @param amount {Number} 
     * @param currencyISOCode {String} 
     */
    constructor(purchaseDate, amount, currencyISOCode) { 
        
        PurchaseDataRowModel.initialize(this, purchaseDate, amount, currencyISOCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, purchaseDate, amount, currencyISOCode) { 
        obj['purchaseDate'] = purchaseDate;
        obj['amount'] = amount;
        obj['currencyISOCode'] = currencyISOCode;
    }

    /**
     * Constructs a <code>PurchaseDataRowModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PurchaseDataRowModel} obj Optional instance to populate.
     * @return {module:model/PurchaseDataRowModel} The populated <code>PurchaseDataRowModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurchaseDataRowModel();

            if (data.hasOwnProperty('purchaseDate')) {
                obj['purchaseDate'] = ApiClient.convertToType(data['purchaseDate'], 'Date');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currencyISOCode')) {
                obj['currencyISOCode'] = ApiClient.convertToType(data['currencyISOCode'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} purchaseDate
 */
PurchaseDataRowModel.prototype['purchaseDate'] = undefined;

/**
 * @member {Number} amount
 */
PurchaseDataRowModel.prototype['amount'] = undefined;

/**
 * @member {String} currencyISOCode
 */
PurchaseDataRowModel.prototype['currencyISOCode'] = undefined;

/**
 * @member {String} category
 */
PurchaseDataRowModel.prototype['category'] = undefined;






export default PurchaseDataRowModel;

