/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyPrequalificationApiClient);
  }
}(this, function(expect, YlThirdPartyPrequalificationApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyPrequalificationApiClient.FinancialDataModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FinancialDataModel', function() {
    it('should create an instance of FinancialDataModel', function() {
      // uncomment below and update the code to test FinancialDataModel
      //var instane = new YlThirdPartyPrequalificationApiClient.FinancialDataModel();
      //expect(instance).to.be.a(YlThirdPartyPrequalificationApiClient.FinancialDataModel);
    });

    it('should have the property monthlyCardRevenue (base name: "monthlyCardRevenue")', function() {
      // uncomment below and update the code to test the property monthlyCardRevenue
      //var instane = new YlThirdPartyPrequalificationApiClient.FinancialDataModel();
      //expect(instance).to.be();
    });

    it('should have the property paymentData (base name: "paymentData")', function() {
      // uncomment below and update the code to test the property paymentData
      //var instane = new YlThirdPartyPrequalificationApiClient.FinancialDataModel();
      //expect(instance).to.be();
    });

    it('should have the property monthlyValueOfPurchaseTransactions (base name: "monthlyValueOfPurchaseTransactions")', function() {
      // uncomment below and update the code to test the property monthlyValueOfPurchaseTransactions
      //var instane = new YlThirdPartyPrequalificationApiClient.FinancialDataModel();
      //expect(instance).to.be();
    });

    it('should have the property purchaseData (base name: "purchaseData")', function() {
      // uncomment below and update the code to test the property purchaseData
      //var instane = new YlThirdPartyPrequalificationApiClient.FinancialDataModel();
      //expect(instance).to.be();
    });

    it('should have the property monthlyRevenueFromInvoices (base name: "monthlyRevenueFromInvoices")', function() {
      // uncomment below and update the code to test the property monthlyRevenueFromInvoices
      //var instane = new YlThirdPartyPrequalificationApiClient.FinancialDataModel();
      //expect(instance).to.be();
    });

    it('should have the property invoiceData (base name: "invoiceData")', function() {
      // uncomment below and update the code to test the property invoiceData
      //var instane = new YlThirdPartyPrequalificationApiClient.FinancialDataModel();
      //expect(instance).to.be();
    });

  });

}));
