/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyPrequalificationApiClient);
  }
}(this, function(expect, YlThirdPartyPrequalificationApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyPrequalificationApiClient.LoanOptionDocument();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoanOptionDocument', function() {
    it('should create an instance of LoanOptionDocument', function() {
      // uncomment below and update the code to test LoanOptionDocument
      //var instane = new YlThirdPartyPrequalificationApiClient.LoanOptionDocument();
      //expect(instance).to.be.a(YlThirdPartyPrequalificationApiClient.LoanOptionDocument);
    });

    it('should have the property fundedAmount (base name: "fundedAmount")', function() {
      // uncomment below and update the code to test the property fundedAmount
      //var instane = new YlThirdPartyPrequalificationApiClient.LoanOptionDocument();
      //expect(instance).to.be();
    });

    it('should have the property fee (base name: "fee")', function() {
      // uncomment below and update the code to test the property fee
      //var instane = new YlThirdPartyPrequalificationApiClient.LoanOptionDocument();
      //expect(instance).to.be();
    });

    it('should have the property loanAmount (base name: "loanAmount")', function() {
      // uncomment below and update the code to test the property loanAmount
      //var instane = new YlThirdPartyPrequalificationApiClient.LoanOptionDocument();
      //expect(instance).to.be();
    });

    it('should have the property sweep (base name: "sweep")', function() {
      // uncomment below and update the code to test the property sweep
      //var instane = new YlThirdPartyPrequalificationApiClient.LoanOptionDocument();
      //expect(instance).to.be();
    });

    it('should have the property currencyISOCode (base name: "currencyISOCode")', function() {
      // uncomment below and update the code to test the property currencyISOCode
      //var instane = new YlThirdPartyPrequalificationApiClient.LoanOptionDocument();
      //expect(instance).to.be();
    });

  });

}));
