/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyPrequalificationApiClient);
  }
}(this, function(expect, YlThirdPartyPrequalificationApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PreQualificationModel', function() {
    it('should create an instance of PreQualificationModel', function() {
      // uncomment below and update the code to test PreQualificationModel
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be.a(YlThirdPartyPrequalificationApiClient.PreQualificationModel);
    });

    it('should have the property thirdPartyMerchantId (base name: "thirdPartyMerchantId")', function() {
      // uncomment below and update the code to test the property thirdPartyMerchantId
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property mid (base name: "mid")', function() {
      // uncomment below and update the code to test the property mid
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "companyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property companyNumber (base name: "companyNumber")', function() {
      // uncomment below and update the code to test the property companyNumber
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property companyType (base name: "companyType")', function() {
      // uncomment below and update the code to test the property companyType
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property companyWebsite (base name: "companyWebsite")', function() {
      // uncomment below and update the code to test the property companyWebsite
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property contactEmailAddress (base name: "contactEmailAddress")', function() {
      // uncomment below and update the code to test the property contactEmailAddress
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property countryISOCode (base name: "countryISOCode")', function() {
      // uncomment below and update the code to test the property countryISOCode
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property loanCurrencyISOCode (base name: "loanCurrencyISOCode")', function() {
      // uncomment below and update the code to test the property loanCurrencyISOCode
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property sicCode (base name: "sicCode")', function() {
      // uncomment below and update the code to test the property sicCode
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property mccCode (base name: "mccCode")', function() {
      // uncomment below and update the code to test the property mccCode
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property monthsTrading (base name: "monthsTrading")', function() {
      // uncomment below and update the code to test the property monthsTrading
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property financialData (base name: "financialData")', function() {
      // uncomment below and update the code to test the property financialData
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

    it('should have the property significantPersons (base name: "significantPersons")', function() {
      // uncomment below and update the code to test the property significantPersons
      //var instane = new YlThirdPartyPrequalificationApiClient.PreQualificationModel();
      //expect(instance).to.be();
    });

  });

}));
