/**
 * YouLend Third Party Pre Qualification API
 * Through this API you can can check if a merchant pre qualifies for a Youlend loan
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddressModel from './model/AddressModel';
import FinancialDataModel from './model/FinancialDataModel';
import InvoiceDataRowModel from './model/InvoiceDataRowModel';
import LoanOptionDocument from './model/LoanOptionDocument';
import PaymentDataRowModel from './model/PaymentDataRowModel';
import PreQualificationModel from './model/PreQualificationModel';
import PreQualificationResultDocument from './model/PreQualificationResultDocument';
import ProblemDetails from './model/ProblemDetails';
import PurchaseDataRowModel from './model/PurchaseDataRowModel';
import SignificantPersonModel from './model/SignificantPersonModel';
import RequestsApi from './api/RequestsApi';


/**
* Through_this_API_you_can_can_check_if_a_merchant_pre_qualifies_for_a_Youlend_loan.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var YlThirdPartyPrequalificationApiClient = require('index'); // See note below*.
* var xxxSvc = new YlThirdPartyPrequalificationApiClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new YlThirdPartyPrequalificationApiClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new YlThirdPartyPrequalificationApiClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new YlThirdPartyPrequalificationApiClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddressModel model constructor.
     * @property {module:model/AddressModel}
     */
    AddressModel,

    /**
     * The FinancialDataModel model constructor.
     * @property {module:model/FinancialDataModel}
     */
    FinancialDataModel,

    /**
     * The InvoiceDataRowModel model constructor.
     * @property {module:model/InvoiceDataRowModel}
     */
    InvoiceDataRowModel,

    /**
     * The LoanOptionDocument model constructor.
     * @property {module:model/LoanOptionDocument}
     */
    LoanOptionDocument,

    /**
     * The PaymentDataRowModel model constructor.
     * @property {module:model/PaymentDataRowModel}
     */
    PaymentDataRowModel,

    /**
     * The PreQualificationModel model constructor.
     * @property {module:model/PreQualificationModel}
     */
    PreQualificationModel,

    /**
     * The PreQualificationResultDocument model constructor.
     * @property {module:model/PreQualificationResultDocument}
     */
    PreQualificationResultDocument,

    /**
     * The ProblemDetails model constructor.
     * @property {module:model/ProblemDetails}
     */
    ProblemDetails,

    /**
     * The PurchaseDataRowModel model constructor.
     * @property {module:model/PurchaseDataRowModel}
     */
    PurchaseDataRowModel,

    /**
     * The SignificantPersonModel model constructor.
     * @property {module:model/SignificantPersonModel}
     */
    SignificantPersonModel,

    /**
    * The RequestsApi service constructor.
    * @property {module:api/RequestsApi}
    */
    RequestsApi
};
